[
  {
    "dblMaterialCategoryMadaster": "Stone",
    "dblMaterialCategoryUniclassName": "Ceramic",
    "dblMaterialCategoryUniclassCode": "Ma_20_13",
    "dblProductCategoryUniclassCode": "Pr_20_93_52_15",
    "dblProductCategoryUniclassName": "Clay bricks",
    "dblCombinedUniclassName": "Ceramic+Clay bricks",
    "dblMaterialCategoryMassDensity": 930,
    "dblMaterialCategoryWasteCategory": "17_01 02",
    "dblMaterialNetVolumeSum": 20.879,
    "dblMaterialWeightSum": 19417.4515,

  },
  {
    "dblMaterialCategoryMadaster": "Stone",
    "dblMaterialCategoryUniclassName": "Gypsum cement",
    "dblMaterialCategoryUniclassCode": "Ma_40_15_35",
    "dblProductCategoryUniclassCode": "Pr_35_31_64_35",
    "dblProductCategoryUniclassName": "Gypsum plasters",
    "dblCombinedUniclassName": "Gypsum cement+Gypsum plasters",
    "dblMaterialCategoryMassDensity": 750,
    "dblMaterialCategoryWasteCategory": "17_08_02",
    "dblMaterialNetVolumeSum": 24.2511,
    "dblMaterialWeightSum": 18188.3609,

  },
  {
    "dblMaterialCategoryMadaster": "Unknown",
    "dblMaterialCategoryUniclassName": "Gypsum cement",
    "dblMaterialCategoryUniclassCode": "Ma_40_15_35",
    "dblProductCategoryUniclassCode": "Pr_25_71_35_65",
    "dblProductCategoryUniclassName": "Gypsum plasterboards",
    "dblCombinedUniclassName": "Gypsum cement+Gypsum plasterboards",
    "dblMaterialCategoryMassDensity": 2100,
    "dblMaterialCategoryWasteCategory": "17_08_02",
    "dblMaterialNetVolumeSum": 4.8173,
    "dblMaterialWeightSum": 10116.4313,
  },
  {
    "dblMaterialCategoryMadaster": "Metal",
    "dblMaterialCategoryUniclassName": "Aluminium",
    "dblMaterialCategoryUniclassCode": "Ma_40_52_03",
    "dblProductCategoryUniclassCode": "Pr_20_76_63_92",
    "dblProductCategoryUniclassName": "Aluminium curtain wall frame sections",
    "dblCombinedUniclassName": "Aluminium+Aluminium curtain wall frame sections",
    "dblMaterialCategoryMassDensity": 2700,
    "dblMaterialCategoryWasteCategory": "17_04_02",
    "dblMaterialNetVolumeSum": 0.4438,
    "dblMaterialWeightSum": 1198.3506,
  },
  {
    "dblMaterialCategoryUniclassName": "Ceramic",
    "dblMaterialCategoryUniclassCode": "Ma_20_13",
    "dblProductCategoryUniclassCode": "Pr_35_93_96_19",
    "dblProductCategoryUniclassName": "Ceramic tiles",
    "dblCombinedUniclassName": "Ceramic+Ceramic tiles",
    "dblMaterialCategoryMassDensity": 2000,
    "dblMaterialCategoryWasteCategory": "17_01_03",
    "dblMaterialNetVolumeSum": 14.931,
    "dblMaterialWeightSum": 29862.0445,
 
  }
]